### ISSUE TITLE
Downloaded ZIP isn't complete.

### ISSUE THREAD

**Issue by GM637** [RayOfIdeas/Godot_GDbot_2D_Demo#1]
Everytime i downloaded the ZIP for the repo or the project, it always got missing files upon extraction. 
Even the project.godot file isn't in the Extracted Folder. Its a hassle trying to download each missing files from the repo by hand.

**Comment by RayOfIdeas** [comment]
My apologies. I updated the `.gitattributes` and `.gitignores`, and caused some files to be excluded upon extraction.

I have tested the [updated release of v0.1.1](https://github.com/RayOfIdeas/Godot_GDbot_2D_Demo/releases/tag/v0.1.1) hopefully it works fine in your machine too.

I'll consider this issue resolved if there's no further reply in a week.
Thank you for giving this demo a shot! 💖😁
